import os
os.system ('pkg install cmatrix -y')
os.system ('clear')
os.system ('pkg install figlet -y')
os.system ('pkg install sl -y')
os.system ('clear')
print ("\033[1;31m")
os.system ('figlet Shop Free Fire')
fx9 = input (" \033[1;33mID Free Fire  ==> ")
fx9 = input (" \033[1;35mDo you want to follow  yes = y no = n ")
if fx9 == 'y' :
        os.system ('clear')
        os.system ('figlet Shop free fire')
        print ("    ERROR  ناﭴﻤ ﻟﺒ رھاوﭴ نﺤﺴًُْ !!")
        print ("")
        print (' \033[1;32m{1}\033[1;33m 120 💎 RIFOND ⚠️❗')
        print ("")
        print (' \033[1;32m{2}\033[1;33m 520 💎 RIFOND ⚠️‼️‼️')
        print ("")
        print (' \033[1;32m{3}\033[1;33m 1100💎 RIFOND ⚠️❌')
        print ("")
        print (' \033[1;32m{4}\033[1;33m 2200💎 RIFOND ⚠️🚫')
        print ("")
        print ('  \033[1;32m \033[1;31m1,2,ﻦﻣ مﻗﺮﻟﺍ ﺮﺘﺧإ')
v7x2 = input (" \033[1;33mmمﻗر بﺘڪأ\033[1;31m==> ")
if v7x2 == '1' :
        os.system ('clear')
        os.system ('termux-open-url https://shop2game.com/result?display_id')
        os.system ('termux-open-url https://shop2game.com/result?display_id')
        print ("Loading..........!")
        os.system ('figlet ')
if fx9 == '2' :
        os.system ('clear')
        os.system ('termux-open-url https://shop2game.com/result?display_id')
        os.system ('termux-open-url https://shop2game.com/result?display_id')
        print ("Loading..........!")
        os.system ('figlet ')
if v7x2 == '3' :
        os.system ('clear')
        os.system ('termux-open-url https://shop2game.com/result?display_id')
        os.system ('termux-open-url https://shop2game.com/result?display_id')
        print ("Loading..........!")
        os.system ('figlet ')
if fx9 == 'y' :
        os.system ('clear')
        os.system ('termux-open-url https://shop2game.com/result?display_id')
        os.system ('termux-open-url https://shop2game.com/result?display_id')
        print ("Loading..........!")
        os.system ('figlet ')
